### ISSUE TITLE
Execution failed for task ':react-native-hms-map:compileDebugJavaWithJavac'.

### ISSUE THREAD

**Issue by arjuntraj** [hms-dtse-dxb/react-native-hms-map#1]
Getting the below error while adding to react-native 60.5
```
/node_modules/react-native-hms-map/android/src/main/java/com/reactlibrary/MapHmsManager.java:297: error: 
method does not override or implement a method from a supertype
    @Override
    ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-hms-map:compileDebugJavaWithJavac'.


```

This is my env details

    "react-native-has-hms": "0.0.2",
    "react-native-hms-map": "0.0.2-u-11",
    "react": "16.10.2",
    "react-native": "0.60.5",

**Comment by hms-dtse-dxb** [comment]
we'll update the library soon, for now try to update your react-native to version 0.61.5

**Comment by rakmobility** [comment]
We have some dependency on RN60.5.
Waiting for the fix ...

**Comment by hms-dtse-dxb** [comment]
this library is now deprecated, refer to the README file to find the link to the official library
